language: rust
rust:
- nightly
before_script:
- rustup component add clippy rustfmt
script:
# only check files that have changed
- git status --porcelain | sed 's/^...//' | grep '\.rs$' | xargs rustfmt --check
- cargo clippy -- -D warnings
- cargo test
