name: Rust

on:
  push:
    branches: [ imlk-dev ]
  pull_request:
    branches: [ imlk-dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup components
      run: rustup component add clippy rustfmt
    - name: Check
      run: |
        cargo fmt --all -- --check
        cargo clippy -- -D warnings
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
